# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perform.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rperform.proto\"\x17\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2+\n\x0bSendService\x12\x1c\n\x08SendData\x12\x08.Message\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=17
  _globals['_MESSAGE']._serialized_end=40
  _globals['_EMPTY']._serialized_start=42
  _globals['_EMPTY']._serialized_end=49
  _globals['_SENDSERVICE']._serialized_start=51
  _globals['_SENDSERVICE']._serialized_end=94
# @@protoc_insertion_point(module_scope)
