# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complicated.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omplicated.proto\"\xf3\x01\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x14\n\x0c\x66loat_number\x18\x03 \x01(\x01\x12\x0c\n\x04\x66lag\x18\x04 \x01(\x08\x12\x13\n\x0bstring_list\x18\x05 \x03(\t\x12+\n\nstring_map\x18\x06 \x03(\x0b\x32\x17.Message.StringMapEntry\x12\x1e\n\x06nested\x18\x07 \x01(\x0b\x32\x0e.NestedMessage\x12\x12\n\nstart_time\x18\x08 \x01(\x03\x1a\x30\n\x0eStringMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\rNestedMessage\x12\x13\n\x0bnested_text\x18\x01 \x01(\t\x12\x15\n\rnested_number\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2+\n\x0bSendService\x12\x1c\n\x08SendData\x12\x08.Message\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complicated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE_STRINGMAPENTRY']._loaded_options = None
  _globals['_MESSAGE_STRINGMAPENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=22
  _globals['_MESSAGE']._serialized_end=265
  _globals['_MESSAGE_STRINGMAPENTRY']._serialized_start=217
  _globals['_MESSAGE_STRINGMAPENTRY']._serialized_end=265
  _globals['_NESTEDMESSAGE']._serialized_start=267
  _globals['_NESTEDMESSAGE']._serialized_end=326
  _globals['_EMPTY']._serialized_start=328
  _globals['_EMPTY']._serialized_end=335
  _globals['_SENDSERVICE']._serialized_start=337
  _globals['_SENDSERVICE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
