# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n\rComplexHeader\x12\x0e\n\x06values\x18\x01 \x03(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x1b.ComplexHeader.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8d\x01\n\x0b\x43omplexData\x12*\n\x07headers\x18\x01 \x03(\x0b\x32\x19.ComplexData.HeadersEntry\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x1a>\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.ComplexHeader:\x02\x38\x01\"\x07\n\x05\x45mpty28\n\rHeaderService\x12\'\n\x0fSendComplexData\x12\x0c.ComplexData\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLEXHEADER_DETAILSENTRY']._loaded_options = None
  _globals['_COMPLEXHEADER_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_COMPLEXDATA_HEADERSENTRY']._loaded_options = None
  _globals['_COMPLEXDATA_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_COMPLEXHEADER']._serialized_start=48
  _globals['_COMPLEXHEADER']._serialized_end=220
  _globals['_COMPLEXHEADER_DETAILSENTRY']._serialized_start=174
  _globals['_COMPLEXHEADER_DETAILSENTRY']._serialized_end=220
  _globals['_COMPLEXDATA']._serialized_start=223
  _globals['_COMPLEXDATA']._serialized_end=364
  _globals['_COMPLEXDATA_HEADERSENTRY']._serialized_start=302
  _globals['_COMPLEXDATA_HEADERSENTRY']._serialized_end=364
  _globals['_EMPTY']._serialized_start=366
  _globals['_EMPTY']._serialized_end=373
  _globals['_HEADERSERVICE']._serialized_start=375
  _globals['_HEADERSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
